# Generated by Django 4.0.1 on 2022-03-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentperformance',
            name='student_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
