# Generated by Django 4.0.1 on 2022-03-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sppapp', '0002_studentperformance_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformance',
            name='assignment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='attendence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='classTest',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='examResult',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='extraCA',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='homeWork',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='quiz',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='readingNotes',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentperformance',
            name='tutorialWatching',
            field=models.FloatField(),
        ),
    ]
